name: GitHub Profile Summary Cards

on:
  schedule: # atualiza todo dia à meia-noite UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente se quiser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.READ_ME }}
        with:
          USERNAME: Viniciu-s

      - name: Substitui TOKEN no README.md pelo segredo
        run: |
          sed -i "s/token=TOKEN/token=${{ secrets.READ_ME }}/g" README.md

      - name: Commit e push do README.md atualizado
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Atualiza README.md com token privado' || echo "Nada para commitar"
          git push
