name: GitHub Profile Summary Cards

on:
  schedule: # atualiza todo dia à meia-noite UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente se quiser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Viniciu-s
      - name: Atualizar README com github-readme-stats
        run: |
          echo '![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=Viniciu-s&hide_progress=true&count_private=true&theme=radical)' > ../README.md
          echo '\n![GitHub stats](https://github-readme-stats.vercel.app/api?username=Viniciu-s&show_icons=true&count_private=true&theme=radical)' >> ../README.md
        env:
          GITHUB_TOKEN: ${{ secrets.README }}
